title: "Daybook"
baseURL: "https://daybook.page"
startedAt: "2026-06-08"
comment:
  enabled: true
  provider: "waline"
  waline:
    serverURL: "https://comment.daybook.page"
    lang: "zh-CN"
    pageSize: 10
    commentSorting: "latest"
    search: false
    imageUploader: false

attachments:
  local_dir: "content/attachments"
  public_path: "/attachments/"
  remote_base_url: "https://static.daybook.page"
  remote_dirs:
    - "audio"
    - "video"
    - "picture"
    - "pdf"
